FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src

COPY ["Shared/ProductSale.Shared/ProductSale.Shared.csproj", "Shared/ProductSale.Shared/"]
COPY ["Services/Catalog/ProductSale.Service.Catalog/ProductSale.Service.Catalog.csproj", "Services/Catalog/ProductSale.Service.Catalog/"]

RUN dotnet restore "Services/Catalog/ProductSale.Service.Catalog/ProductSale.Service.Catalog.csproj"

COPY . .

WORKDIR "/src/Services/Catalog/ProductSale.Service.Catalog"
RUN dotnet build "ProductSale.Service.Catalog.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ProductSale.Service.Catalog.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet","ProductSale.Service.Catalog.dll"]