version: '3.8'
services:
  catalogdb:
    image: mongo
  basketdb: 
    image: redis
  discountdb:
    image: postgres
  identitydb:
    image: mcr.microsoft.com/mssql/server:2019-latest 
  orderdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
  rabbitmq:
    image: rabbitmq:3-management
  
  catalog.api:
    image: catalog_api_image
    build: 
        context: .
        dockerfile: Services/Catalog/ProductSale.Service.Catalog/DockerFile
  
  identityserver.api:
    image: identityserver_api_image
    build:
        context: .
        dockerfile: IdentityServer/ProductSale.IdentityServer/DockerFile

volumes:
  catalogdb_volume:
  discountdb_volume:
  identitydb_volume:
  orderdb_volume: 