FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS runtime
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src

COPY ["Services/Photo/ProductSale.Service.Photo/ProductSale.Service.Photo.csproj", "Services/Photo/ProductSale.Service.Photo/"]

RUN dotnet restore "Services/Photo/ProductSale.Service.Photo/ProductSale.Service.Photo.csproj"

COPY . .

WORKDIR "/src/Services/Photo/ProductSale.Service.Photo"

RUN dotnet build "ProductSale.Service.Photo.csproj" -c Release -o /app/build

FROM build AS publish
RUN  dotnet publish "ProductSale.Service.Photo.csproj" -c Release -o /app/publish

FROM runtime AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT [ "dotnet", "ProductSale.Service.Photo.dll"]