FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src

COPY ["Gateway/ProductSale.Gateway/ProductSale.Gateway.csproj", "Gateway/ProductSale.Gateway/"]

RUN dotnet restore "Gateway/ProductSale.Gateway/ProductSale.Gateway.csproj"

COPY . .

WORKDIR "/src/Gateway/ProductSale.Gateway"
RUN dotnet build "ProductSale.Gateway.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ProductSale.Gateway.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet","ProductSale.Gateway.dll"]