FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src

COPY ["Shared/ProductSale.Shared/ProductSale.Shared.csproj", "Shared/ProductSale.Shared/"]
COPY ["Services/Order/ProductSale.Services.Order.Core/ProductSale.Services.Order.Core.csproj", "Services/Order/ProductSale.Services.Order.Core/"]
COPY ["Services/Order/ProductSale.Services.Order.BL/ProductSale.Services.Order.BL.csproj", "Services/Order/ProductSale.Services.Order.BL/"]
COPY ["Services/Order/ProductSale.Services.Order.DAL/ProductSale.Services.Order.DAL.csproj", "Services/Order/ProductSale.Services.Order.DAL/"]
COPY ["Services/Order/ProductSale.Services.Order.API/ProductSale.Services.Order.API.csproj", "Services/Order/ProductSale.Services.Order.API/"]

RUN dotnet restore "Services/Order/ProductSale.Services.Order.API/ProductSale.Services.Order.API.csproj"

COPY . .

WORKDIR "/src/Services/Order/ProductSale.Services.Order.API"

RUN dotnet build "ProductSale.Services.Order.API.csproj" -c Release -o /app/build

FROM build as publish
RUN dotnet publish "ProductSale.Services.Order.API.csproj" -c Release -o /app/publish

FROM base as final
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT [ "dotnet", "ProductSale.Services.Order.API.dll" ]