FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src

COPY ["Shared/ProductSale.Shared/ProductSale.Shared.csproj", "Shared/ProductSale.Shared/"]
COPY ["Services/Basket/ProductSale.Service.Basket/ProductSale.Service.Basket.csproj", "Services/Basket/ProductSale.Service.Basket/"]

RUN dotnet restore "Services/Basket/ProductSale.Service.Basket/ProductSale.Service.Basket.csproj"

COPY . .

WORKDIR "/src/Services/Basket/ProductSale.Service.Basket"
RUN dotnet build "ProductSale.Service.Basket.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ProductSale.Service.Basket.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet","ProductSale.Service.Basket.dll"]
