FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src

COPY ["Shared/ProductSale.Shared/ProductSale.Shared.csproj", "Shared/ProductSale.Shared/"]
COPY ["Clients/ProductSale.Web/ProductSale.Web.csproj", "Clients/ProductSale.Web/"]

RUN dotnet restore "Clients/ProductSale.Web/ProductSale.Web.csproj"

COPY . .

WORKDIR "/src/Clients/ProductSale.Web"
RUN dotnet build "ProductSale.Web.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ProductSale.Web.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet","ProductSale.Web.dll"]